services:
  db:
    container_name: db
    image: postgres:13
    evironment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes: 
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}

// https://www.youtube.com/watch?v=XDHDTGoZ_68&t=3775s

